### ISSUE TITLE
Missing indices on TF_DCSA_OPS

### ISSUE THREAD

**Issue by rkurman** [hiconic-os/tribefire.extension.vitals.jdbc#4]
As far as I understand the table creation code in `GmDbDcsaSharedStorage` the table `TF_DCSA_OPS` gets created without any indices. When it reads operations, the `accessId` is part of the query, resulting in a full table scan with each access.
Shouldn't we add an index for the accessId as well (incl. code for adapting an existing table)?

**Comment by pgazdik** [comment]
I have added an index that corresponds to the query: https://github.com/hiconic-os/tribefire.extension.vitals.jdbc/commit/8e25f08512eb9d646d38fb761a6b73a7ef532ca9

There are tests, but not for a pre-existing table, so please verify there is no issue. The index will be created, that should not be the problem.

**Comment by rkurman** [comment]
Works perfectly. I also tested the creation of the index with an existing table. Thank you!
